const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
        name: "Free Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt2.jpg",
        price: 70,
        brand: "armoured",
        rating: 4.5,
        numReviews: 6,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Free Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt3.jpg",
        price: 54,
        brand: "Nike",
        rating: 4.5,
        numReviews: 4,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Free Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt4.jpg",
        price: 100,
        brand: "addidas",
        rating: 4.5,
        numReviews: 3,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Free Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt5.jpg",
        price: 70,
        brand: "addidas",
        rating: 4.5,
        numReviews: 8,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Free Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt6.jpg",
        price: 100,
        brand: "Nike",
        rating: 4.5,
        numReviews: 9,
        countInStock: 20,
        description: "A popular shirt",
      },
  ],
};
 
export  default data;